create table if not exists public.category_options (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 80),
  direction text not null default 'debit' check (direction in ('debit', 'credit')),
  created_at timestamptz not null default now()
);

create unique index if not exists category_options_name_lower_idx
  on public.category_options (lower(name));

insert into public.category_options (name, direction)
values
  ('SN CONTABILIDADE', 'debit'),
  ('ASAAS MARKETING', 'debit'),
  ('ASAAS ROYALTIES', 'debit'),
  ('SLS LOC OFICINA', 'debit'),
  ('PREF.SOROCABA', 'debit'),
  ('SLS - GESTÃO DA FROTA', 'debit'),
  ('ASAAS - ADESÃO DAS MOTOS', 'debit'),
  ('RECEITA', 'credit'),
  ('OUTRO', 'debit')
on conflict do nothing;

alter table public.category_options enable row level security;

drop policy if exists "Public can read category options" on public.category_options;
create policy "Public can read category options"
  on public.category_options
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can create category options" on public.category_options;
create policy "Public can create category options"
  on public.category_options
  for insert
  to anon, authenticated
  with check (true);

grant select, insert on table public.category_options to anon, authenticated;
grant usage, select on sequence public.category_options_id_seq to anon, authenticated;
